# .github/workflows/download-music.yml

name: Download Music from README

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'  # <-- 必须是 README.md

  workflow_dispatch:

jobs:
  download_music_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run music download script
        run: python download_music.py README.md  # <-- 必须是 README.md

      - name: Commit downloaded files
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ ! -d "downloads" ]; then exit 0; fi
          git add downloads/
          if git diff --staged --quiet && git diff --quiet; then
            echo "No file changes to commit."
          else
            git commit -m "sync(music): Update music library from README [skip ci]"
            git push
            echo "Committed file changes successfully."
          fi
